


workflows:
  build:
    name: Build APK and iOS app
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build iOS IPA
        script: flutter build ipa --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/Runner.ipa
    environment:
      flutter: stable
      xcode: latest
    publishing:
      email:
        recipients:
          - r00t-x@outlook.com
